export enum GameEvent {
    UPDATE = "UPDATE",
    SAVE = "SAVE",
    LOAD = "LOAD",
    PAGE_RELOAD = "PAGE_RELOAD",

    MOUSE_MOVE = "MOUSE_MOVE",
    MOUSE_WHEEL = "MOUSE_WHEEL",
    MOUSE_UP = "MOUSE_UP",
    RIGHT_MOUSE_UP = "RIGHT_MOUSE_UP",

    KEY_DOWN = "KEY_DOWN",
    KEY_UP = "KEY_UP",

    WINDOW_LOST_FOCUS = "WINDOW_LOST_FOCUS",
    WINDOW_GAINED_FOCUS = "WINDOW_GAINED_FOCUS",

    OPTIONS_OPENED = "OPTIONS_OPENED",
    HARD_RESET_ABORT = "HARD_RESET_ABORT",
    OPEN_REPO_LINK = "OPEN_REPO_LINK",

    SOUNDS_ON = "SOUNDS_ON",
    SOUNDS_OFF = "SOUNDS_OFF",
    MUSIC_ON = "MUSIC_ON",
    MUSIC_OFF = "MUSIC_OFF",

    ACHIEVEMENT_UNLOCKED = "ACHIEVEMENT_UNLOCKED",
    ACHIEVEMENTS_UNLOCKED = "ACHIEVEMENTS_UNLOCKED",
    ACHIEVEMENT_PROGRESS = "ACHIEVEMENT_PROGRESS",
    ACHIEVEMENT_COMPLETED = "ACHIEVEMENT_COMPLETED",

    ACHIEVEMENT_CLICKED = "ACHIEVEMENT_CLICKED",
    ACHIEVEMENT_MOUSE_ENTER = "ACHIEVEMENT_MOUSE_ENTER",

    ACHIEVEMENT_POINTS_CHANGED = "ACHIEVEMENT_POINTS_CHANGED",

    UPGRADE_UNLOCKED = "UPGRADE_UNLOCKED",
    UPGRADE_PURCHASED = "UPGRADE_PURCHASED",

    GAME_MECHANIC_UNLOCKED = "GAME_MECHANIC_UNLOCKED",

    THE_BUTTON_UNLOCKED = "THE_BUTTON_UNLOCKED",
    THE_BUTTON_MOUSE_ENTER = "THE_BUTTON_MOUSE_ENTER",
    THE_BUTTON_MOUSE_LEAVE = "THE_BUTTON_MOUSE_LEAVE",
    THE_BUTTON_MOUSE_DOWN = "THE_BUTTON_MOUSE_DOWN",
    THE_BUTTON_MOUSE_UP = "THE_BUTTON_MOUSE_UP",
    THE_BUTTON_CLICK = "THE_BUTTON_MOUSE_CLICK",

    THE_DICE_UNLOCKED = "THE_DICE_UNLOCKED",
    THE_DICE_NEW_DIE = "THE_DICE_NEW_DIE",
    THE_DICE_ROLL = "THE_DICE_ROLL",
    THE_DICE_ROLLER_UNLOCKED = "THE_DICE_ROLLER_UNLOCKED",

    THE_SWITCH_UNLOCKED = "THE_SWITCH_UNLOCKED",
    THE_SWITCH_SWITCH = "THE_SWITCH_SWITCH",

    GENERATOR_START = "GENERATOR_START",
    REGRET = "REGRET",

    THE_END = "THE_END"
}